name: ecommerce_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  provider: ^6.0.2
  flutter_bloc: ^8.0.1

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: icons_font/MyFlutterApp.ttf
    - family: CategoryIcons
      fonts:
        - asset: icons_font/CategoryIcons.ttf
    - family: MarkPronormal400
      fonts:
        - asset: fonts/MARKPRO.OTF
          weight: 400
    - family: MarkPronormal500
      fonts:
        - asset: fonts/MARKPRO.OTF
          weight: 500
    - family: MarkPronormal700
      fonts:
        - asset: fonts/MARKPRO.OTF
          weight: 700
    - family: MarkPronormal800
      fonts:
        - asset: fonts/MARKPRO.OTF
          weight: 800
    - family: MarkProbold
      fonts:
        - asset: fonts/MARKPRO-BOLD.OTF
    - family: MyIcons
      fonts:
        - asset: icons_font/MyIcons.ttf
    - family: SFPro
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400

  assets:
    - assets/
    - assets/icons/
  uses-material-design: true
